### ISSUE TITLE
make error: undefined reference to opencv

### ISSUE THREAD

**Issue by 8T15Bin** [yan99033/MiDaS-cpp#1]
Hi, I'm trying to compile your code using c++17 and opencv4.2. But I've been encountering an linking error:
```

[100%] Linking CXX executable midas_inference
/usr/bin/ld: CMakeFiles/midas_inference.dir/src/inference_midas.cpp.o: in function `main':
inference_midas.cpp:(.text.startup+0x6c): undefined reference to `cv::imread(std::string const&, int)'
/usr/bin/ld: inference_midas.cpp:(.text.startup+0x428): undefined reference to `cv::namedWindow(std::string const&, int)'
/usr/bin/ld: inference_midas.cpp:(.text.startup+0x47a): undefined reference to `cv::imshow(std::string const&, cv::_InputArray const&)'
/usr/bin/ld: libmidas_lib.so: undefined reference to `cv::error(int, std::string const&, char const*, char const*, int)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/midas_inference.dir/build.make:149: midas_inference] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/midas_inference.dir/all] Error 2
make: *** [Makefile:85: all] Error 2
```

Do you have any idea how to fix this?

**Comment by yan99033** [comment]
Linking issue sometimes can be hard to fix. Normally I would print out the libraries and the include directories of the problematic link. That being said, you can add the following lines to your CMakeLists.txt:

message(STATUS "OpenCV library status:")
message(STATUS "    config: ${OpenCV_DIR}")
message(STATUS "    version: ${OpenCV_VERSION}")
message(STATUS "    libraries: ${OpenCV_LIBS}")
message(STATUS "    include path: ${OpenCV_INCLUDE_DIRS}")

Make sure that you add them after the line `FIND_PACKAGE(OpenCV REQUIRED)`. If the terminal does not print out the OpenCV libraries and include directories, then you might need to do something about it.

**Comment by yan99033** [comment]
I am going to close the issue. Feel free to re-open if the debugging step does not help to solve the problem.

**Comment by nakul3112** [comment]
hi @yan99033 ,

   I made a conda environment with libtorch and opencv, but when I run a basic C++ code, I get the same above mentioned OpenCV: undefined reference error.  After printing the debug messages in CMakeLists, it shows that OpenCV_DIR path is somewhere in anaconda environment, I am not sure if there is version mismatch or something else. Any help in this issue would be greatly appreciated.

Regards,
Nakul
