### ISSUE TITLE
Problem when link ld_libraries to inference_midas

### ISSUE THREAD

**Issue by KunB-Fighting** [yan99033/MiDaS-cpp#3]
Hi, I meet a problem during link

`/usr/bin/ld: CMakeFiles/midas_inference.dir/src/inference_midas.cpp.o: in function `main':
inference_midas.cpp:(.text.startup+0x6c): undefined reference to `cv::imread(std::string const&, int)'
/usr/bin/ld: inference_midas.cpp:(.text.startup+0x350): undefined reference to `cv::namedWindow(std::string const&, int)'
/usr/bin/ld: inference_midas.cpp:(.text.startup+0x3a2): undefined reference to `cv::imshow(std::string const&, cv::_InputArray const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/midas_inference.dir/build.make:155: midas_inference] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/midas_inference.dir/all] Error 2
make: *** [Makefile:84: all] Error 2`

enviroment:
Ubuntu 20.04
opencv 4.5.2

What I have tried:
1.re-compile the opencv lib from source, and add the path to  CMAKE_PREFIX_PATH, and output the include_dir of opencv, it seems alright, but I still meet the problem above, the output of cmake is 

`-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "11.1") 
-- Caffe2: CUDA detected: 11.1
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 11.1
-- Found CUDNN: /usr/local/cuda/lib64/libcudnn.so  
-- Found cuDNN: v8.0.4  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
CMake Warning at /home/kunbpc/Installed/libtorch/libtorch-shared-with-deps-1.8.0+cu111/libtorch/share/cmake/Caffe2/public/cuda.cmake:198 (message):
  Failed to compute shorthash for libnvrtc.so
Call Stack (most recent call first):
  /home/kunbpc/Installed/libtorch/libtorch-shared-with-deps-1.8.0+cu111/libtorch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  /home/kunbpc/Installed/libtorch/libtorch-shared-with-deps-1.8.0+cu111/libtorch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:18 (FIND_PACKAGE)

-- Autodetected CUDA architecture(s):  8.6
-- Added CUDA NVCC flags for: -gencode;arch=compute_86,code=sm_86
-- Found Torch: /home/kunbpc/Installed/libtorch/libtorch-shared-with-deps-1.8.0+cu111/libtorch/lib/libtorch.so  
-- Found OpenCV: /usr/local (found suitable version "4.5.2", minimum required is "4") 
-- Found PythonLibs: /home/kunbpc/Installed/Anaconda3/lib/libpython3.8.so (found version "3.8.5") 
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: python numpy 
-- OpenCV_INCLUDE_DIRS : /usr/local/include/opencv4
-- TORCH_LIBRARIES : torchtorch_library/home/kunbpc/Installed/libtorch/libtorch-shared-with-deps-1.8.0+cu111/libtorch/lib/libc10.so/usr/local/cuda/lib64/stubs/libcuda.so/usr/local/cuda/lib64/libnvrtc.so/usr/local/cuda/lib64/libnvToolsExt.so/usr/local/cuda/lib64/libcudart.so/home/kunbpc/Installed/libtorch/libtorch-shared-with-deps-1.8.0+cu111/libtorch/lib/libc10_cuda.so
-- TORCH_INCLUDE_DIRS : /home/kunbpc/Installed/libtorch/libtorch-shared-with-deps-1.8.0+cu111/libtorch/include/home/kunbpc/Installed/libtorch/libtorch-shared-with-deps-1.8.0+cu111/libtorch/include/torch/csrc/api/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kunbpc/Codes/depth/MiDaS-cpp/build`

2. I have tried to add a linker flag in cmakelist.txt,  it is useless and I comments out it then.

`SET(GGC_OPENCV_LINK_FLAG "-lopencv_highgui")
SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${GGC_OPENCV_LINK_FLAG}")`

**Comment by yan99033** [comment]
When there are undefined reference problems, they normally mean that you have provided the header files, but the linker is not able to find the libraries. Check your `OpenCV_LIBRARIES`

**Comment by KunB-Fighting** [comment]
Thanks for your reply, I check the `OpenCV_LIBRARIES` and check the compile command line, and the outputs are

`
-- OpenCV_LIBRARIES : opencv_calib3dopencv_coreopencv_dnnopencv_features2dopencv_flannopencv_gapiopencv_highguiopencv_imgcodecsopencv_imgprocopencv_mlopencv_objdetectopencv_photoopencv_stitchingopencv_videoopencv_videoioopencv_alphamatopencv_arucoopencv_bgsegmopencv_bioinspiredopencv_ccalibopencv_datasetsopencv_dnn_objdetectopencv_dnn_superresopencv_dpmopencv_faceopencv_fuzzyopencv_hdfopencv_hfsopencv_img_hashopencv_intensity_transformopencv_line_descriptoropencv_mccopencv_optflowopencv_phase_unwrappingopencv_plotopencv_qualityopencv_rapidopencv_regopencv_rgbdopencv_saliencyopencv_sfmopencv_shapeopencv_stereoopencv_structured_lightopencv_superresopencv_surface_matchingopencv_textopencv_trackingopencv_videostabopencv_wechat_qrcodeopencv_xfeatures2dopencv_ximgprocopencv_xobjdetectopencv_xphoto`

`[100%] Linking CXX executable midas_inference
/usr/bin/cmake -E cmake_link_script CMakeFiles/midas_inference.dir/link.txt --verbose=1
/usr/bin/c++   -std=c++14 -fPIC -std=c++14 -fPIC -O3 -DNDEBUG   -lopencv_highgui -rdynamic CMakeFiles/midas_inference.dir/src/inference_midas.cpp.o  -o midas_inference  -Wl,-rpath,/home/kunbpc/Codes/depth/MiDaS-cpp/build:/usr/local/lib:/home/kunbpc/Installed/Anaconda3/lib:/home/kunbpc/Installed/libtorch/libtorch-shared-with-deps-1.8.0+cu111/libtorch/lib:/usr/local/cuda/lib64:/usr/local/cuda/lib64/stubs libmidas_lib.so /usr/local/lib/libopencv_gapi.so.4.5.2 /usr/local/lib/libopencv_stitching.so.4.5.2 /usr/local/lib/libopencv_alphamat.so.4.5.2 /usr/local/lib/libopencv_aruco.so.4.5.2 /usr/local/lib/libopencv_bgsegm.so.4.5.2 /usr/local/lib/libopencv_bioinspired.so.4.5.2 /usr/local/lib/libopencv_ccalib.so.4.5.2 /usr/local/lib/libopencv_dnn_objdetect.so.4.5.2 /usr/local/lib/libopencv_dnn_superres.so.4.5.2 /usr/local/lib/libopencv_dpm.so.4.5.2 /usr/local/lib/libopencv_face.so.4.5.2 /usr/local/lib/libopencv_fuzzy.so.4.5.2 /usr/local/lib/libopencv_hdf.so.4.5.2 /usr/local/lib/libopencv_hfs.so.4.5.2 /usr/local/lib/libopencv_img_hash.so.4.5.2 /usr/local/lib/libopencv_intensity_transform.so.4.5.2 /usr/local/lib/libopencv_line_descriptor.so.4.5.2 /usr/local/lib/libopencv_mcc.so.4.5.2 /usr/local/lib/libopencv_quality.so.4.5.2 /usr/local/lib/libopencv_rapid.so.4.5.2 /usr/local/lib/libopencv_reg.so.4.5.2 /usr/local/lib/libopencv_rgbd.so.4.5.2 /usr/local/lib/libopencv_saliency.so.4.5.2 /usr/local/lib/libopencv_sfm.so.4.5.2 /usr/local/lib/libopencv_stereo.so.4.5.2 /usr/local/lib/libopencv_structured_light.so.4.5.2 /usr/local/lib/libopencv_phase_unwrapping.so.4.5.2 /usr/local/lib/libopencv_superres.so.4.5.2 /usr/local/lib/libopencv_optflow.so.4.5.2 /usr/local/lib/libopencv_surface_matching.so.4.5.2 /usr/local/lib/libopencv_tracking.so.4.5.2 /usr/local/lib/libopencv_highgui.so.4.5.2 /usr/local/lib/libopencv_datasets.so.4.5.2 /usr/local/lib/libopencv_plot.so.4.5.2 /usr/local/lib/libopencv_text.so.4.5.2 /usr/local/lib/libopencv_videostab.so.4.5.2 /usr/local/lib/libopencv_videoio.so.4.5.2 /usr/local/lib/libopencv_wechat_qrcode.so.4.5.2 /usr/local/lib/libopencv_xfeatures2d.so.4.5.2 /usr/local/lib/libopencv_ml.so.4.5.2 /usr/local/lib/libopencv_shape.so.4.5.2 /usr/local/lib/libopencv_ximgproc.so.4.5.2 /usr/local/lib/libopencv_video.so.4.5.2 /usr/local/lib/libopencv_dnn.so.4.5.2 /usr/local/lib/libopencv_xobjdetect.so.4.5.2 /usr/local/lib/libopencv_imgcodecs.so.4.5.2 /usr/local/lib/libopencv_objdetect.so.4.5.2 /usr/local/lib/libopencv_calib3d.so.4.5.2 /usr/local/lib/libopencv_features2d.so.4.5.2 /usr/local/lib/libopencv_flann.so.4.5.2 /usr/local/lib/libopencv_xphoto.so.4.5.2 /usr/local/lib/libopencv_photo.so.4.5.2 /usr/local/lib/libopencv_imgproc.so.4.5.2 /usr/local/lib/libopencv_core.so.4.5.2 /home/kunbpc/Installed/Anaconda3/lib/libpython3.8.so /usr/lib/x86_64-linux-gnu/libboost_numpy38.so.1.71.0 /usr/lib/x86_64-linux-gnu/libboost_python38.so.1.71.0 /home/kunbpc/Installed/libtorch/libtorch-shared-with-deps-1.8.0+cu111/libtorch/lib/libtorch.so -Wl,--no-as-needed,"/home/kunbpc/Installed/libtorch/libtorch-shared-with-deps-1.8.0+cu111/libtorch/lib/libtorch_cuda.so" -Wl,--as-needed -Wl,--no-as-needed,"/home/kunbpc/Installed/libtorch/libtorch-shared-with-deps-1.8.0+cu111/libtorch/lib/libtorch_cuda_cu.so" -Wl,--as-needed -Wl,--no-as-needed,"/home/kunbpc/Installed/libtorch/libtorch-shared-with-deps-1.8.0+cu111/libtorch/lib/libtorch_cpu.so" -Wl,--as-needed -lpthread /home/kunbpc/Installed/libtorch/libtorch-shared-with-deps-1.8.0+cu111/libtorch/lib/libc10_cuda.so /home/kunbpc/Installed/libtorch/libtorch-shared-with-deps-1.8.0+cu111/libtorch/lib/libc10.so /usr/local/cuda/lib64/libcufft.so /usr/local/cuda/lib64/libcurand.so /usr/local/cuda/lib64/libcublas.so /usr/local/cuda/lib64/libcudnn.so -Wl,--no-as-needed,"/home/kunbpc/Installed/libtorch/libtorch-shared-with-deps-1.8.0+cu111/libtorch/lib/libtorch_cuda_cpp.so" -Wl,--as-needed -Wl,--no-as-needed,"/home/kunbpc/Installed/libtorch/libtorch-shared-with-deps-1.8.0+cu111/libtorch/lib/libtorch.so" -Wl,--as-needed /home/kunbpc/Installed/libtorch/libtorch-shared-with-deps-1.8.0+cu111/libtorch/lib/libc10.so /usr/local/cuda/lib64/stubs/libcuda.so /usr/local/cuda/lib64/libnvrtc.so /usr/local/cuda/lib64/libnvToolsExt.so /usr/local/cuda/lib64/libcudart.so /home/kunbpc/Installed/libtorch/libtorch-shared-with-deps-1.8.0+cu111/libtorch/lib/libc10_cuda.so 
/usr/bin/ld: CMakeFiles/midas_inference.dir/src/inference_midas.cpp.o: in function `main':
inference_midas.cpp:(.text.startup+0x6c): undefined reference to `cv::imread(std::string const&, int)'
/usr/bin/ld: inference_midas.cpp:(.text.startup+0x350): undefined reference to `cv::namedWindow(std::string const&, int)'
/usr/bin/ld: inference_midas.cpp:(.text.startup+0x3a2): undefined reference to `cv::imshow(std::string const&, cv::_InputArray const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/midas_inference.dir/build.make:155: midas_inference] Error 1
make[2]: Leaving directory '/home/kunbpc/Codes/depth/MiDaS-cpp/build'
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/midas_inference.dir/all] Error 2
make[1]: Leaving directory '/home/kunbpc/Codes/depth/MiDaS-cpp/build'
make: *** [Makefile:84: all] Error 2`

It seems that the command line is alright, but I still meet the same problem

**Comment by KunB-Fighting** [comment]
Hi, I have tested opencv with a toy example, which only contains opencv and show the bicycle.jpg, it works well.
But when I add midas model into the code, there would be an error with cv::imread, cv::namedwindow and cv::inshow

**Comment by KunB-Fighting** [comment]
Hi, thanks for your help, I solved the problem by recompile opencv and use libtorch-cxx11 instead of pre-cxx11. I don not know what caused the problem, but I succeed compile and run this demo. Thanks for your great work and thanks for your reply!!

**Comment by yan99033** [comment]
Thanks for the feedback. In future projects, I might consider using a Docker container so that everyone can just use the pre-configured libraries.

**Comment by KunB-Fighting** [comment]
Additionally, it seems that libtorch may break the link of other libs, 

> I would like to add that it would be nice to document the usage of `-D_GLIBCXX_USE_CXX11_ABI` here: https://pytorch.org/cppdocs/installing.html
> 
> Currently the usage of `find_package(Torch REQUIRED)` is likely to break the linking process to other third party libraries and the resulting error messages can be misleading, hard to debug and ultimately developers can spend a lot of time to understand what's going on.
> 
> I am not sure if it is good practise to set this flag in the `TorchConfig.cmake`, I would suggest to add a warning and to refer to documentation for further reading.
> 
> _Originally posted by @martinruenz in https://github.com/pytorch/pytorch/issues/17492#issuecomment-471044512_

it may be better to compile the library and the inference seperately and link the opencv latter(or twice) to avoid some potential problems.
